title: Sophie's Artwork

url: sophiegreenfield.github.io
baseurl: ""

# Directory layout
destination:  _site/
layouts_dir:  _layouts/
data_dir:     _data/
includes_dir: _includes/
sass_dir:     _sass/

exclude: [Gemfile*, README.md]

collections:
  pages:
    output: true
    permalink: /:path

# Rendering
markdown: kramdown
kramdown:
  input: GFM  # Github-Flavoured Markdown
